const ERROR_CODES = {
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_PHONE: 'AUTH_INVALID_PHONE',

  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

module.exports = { ERROR_CODES };
