const ERROR_CODES = {
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_PHONE: 'AUTH_INVALID_PHONE',
  AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
  AUTH_INVALID_VERIFY_CODE: 'AUTH_INVALID_VERIFY_CODE',
  AUTH_PHONE_EXISTS: 'AUTH_PHONE_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',

  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

module.exports = { ERROR_CODES };
